// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:064fa81c-9ec7-4fed-ad13-a3f54de39319",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_fWbOPPSaj",
    "aws_user_pools_web_client_id": "4b2rsh0da16vo8g74fmicseion",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "dynamo2352b6c0-local",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
